services:
  db:
    image: postgres:16
    container_name: shipper_postgres
    environment:
      POSTGRES_USER: shipper
      POSTGRES_PASSWORD: shipper_password
      POSTGRES_DB: shipper_db
    ports:
      - "5432:5432"
    volumes:
      - shipper_pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: shipper_fastapi
    env_file:
      - ./backend/.env.example
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: shipper_nextjs
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      INTERNAL_API_URL: http://backend:8000
      NEXT_PUBLIC_WS_URL: ws://localhost:8000/ws/locations
      NEXT_PUBLIC_MAP_MODE: local
      NEXT_PUBLIC_PMTILES_URL: /maps/hcm.pmtiles
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  shipper_pgdata:
